# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AllInOne' do

use_frameworks!
pod 'SnapKit', '~> 4.0.0'
pod 'FSCalendar'
pod 'SwiftyJSON'
pod 'Hue'
pod 'Alamofire'
pod 'HRQRCodeScanTool'
pod 'SteviaLayout'
pod 'CLToast'

end
