# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AllInOne' do

use_frameworks!
pod 'SnapKit', '~> 4.0.0'
pod 'FSCalendar'
pod 'Alamofire', '~> 4.7'
pod 'SwiftyJSON'
pod 'Hue'
end
